### ISSUE TITLE
Enable Mathjax

### ISSUE THREAD

**Issue by suhr** [tox-rs/book#10]
Right now, tox-human does not render latex formulas.

EDIT: `mathjax-support` is set to true. So the problem is with using `$` as the delimiter. The mdbook doc proposed using `\\( \\)` instead.

**Comment by kpp** [comment]
What for?

**Comment by suhr** [comment]
For example, a part of onion client doc:

> `Set path_num = r(random_u32(), NUMBER_ONION_PATHS) + path_index, where $r(a, n) = a - (a \bmod n)$ – a “modulo rounding” function`
