### ISSUE TITLE
Rename tox-rs/tox-human to tox-rs/book

### ISSUE THREAD

**Issue by kpp** [tox-rs/book#12]
Vote:

- [x] @kpp 
- [x] @NamsooCho 
- [ ] @kurnevsky 
- [x] @suhr

**Comment by suhr** [comment]
Right now it looks more like a collection of development notes rather than a book.

**Comment by kpp** [comment]
Yes. And we are going to extend it.

**Comment by suhr** [comment]
Well, I planned to do something like that, but much later.

Anyway, if this is going to be a book, we need to change the structure a bit. The SUMMARY.md probably should look like this:

```
# Summary

[Introduction](intro.md)

- [Cryptography](crypto/crypto.md)
- [Network](net/net.md)
- [DHT](dht/dht.md)
- [TCP Relay](relay/relay.md)
- [Onion](onion/onion.md)
- [Transport Protocol](transport/transport.md)
- [Messenger](msg/msg.md)
- [Groupchats](group/group.md)
```

**Comment by kpp** [comment]
I like it.
