### ISSUE TITLE
Change the doc structure

### ISSUE THREAD

**Issue by kpp** [tox-rs/book#15]
by @suhr

The SUMMARY.md probably should look like this:

```
# Summary

[Introduction](intro.md)

- [Cryptography](crypto/crypto.md)
- [Network](net/net.md)
- [DHT](dht/dht.md)
- [TCP Relay](relay/relay.md)
- [Onion](onion/onion.md)
- [Transport Protocol](transport/transport.md)
- [Messenger](msg/msg.md)
- [Groupchats](group/group.md)
```

**Comment by suhr** [comment]
There's an issue with mdbook: it [does not support empty chapters](https://github.com/rust-lang-nursery/mdBook/issues/576). The corresponding [PR](https://github.com/rust-lang-nursery/mdBook/pull/592) is closed because it's almost a year old and there's nobody to revive it.

**Comment by kpp** [comment]
Fill empty chapters with "TO BE DONE..."
